{ ... }:
{
  imports = [
    ./alacritty.nix
    ./alvr.nix
    ./amd.nix
    ./android.nix
    ./appimage.nix
    ./ascension.nix
    ./aws.nix
    ./baldursgate3.nix
    ./bashly.nix
    ./blueman.nix
    ./boot.nix
    ./caddy.nix
    ./certificates.nix
    ./chntpw.nix
    ./clipboard.nix
    ./coolercontrol.nix
    ./corectrl.nix
    ./corsair.nix
    ./curseforge.nix
    ./dbeaver.nix
    ./direnv.nix
    ./discord.nix
    ./display.nix
    ./earlyoom.nix
    ./elm.nix
    ./envision.nix
    ./execline.nix
    ./firefox.nix
    ./firmware.nix
    ./fish.nix
    ./flashfocus.nix
    ./flatpak.nix
    ./font.nix
    ./foot.nix
    ./fstrim.nix
    ./gammastep.nix
    ./gcloud
    ./gdb.nix
    ./gemini
    ./gephi.nix
    ./gimp.nix
    ./git.nix
    ./golang.nix
    ./google-chrome.nix
    ./gopass.nix
    ./gparted.nix
    ./gpgssh.nix
    ./graphviz.nix
    ./grpcurl.nix
    ./haskell.nix
    ./homemanager.nix
    ./imv.nix
    ./inkscape.nix
    ./javascript.nix
    ./kanata.nix
    ./kanshi.nix
    ./keyd.nix
    ./kubernetes.nix
    ./light.nix
    ./lllm
    ./location.nix
    ./mako.nix
    ./matrix.nix
    ./media.nix
    ./minio.nix
    ./mpv.nix
    ./nemo.nix
    ./neovim.nix
    ./network.nix
    ./network.nix
    ./nix-index.nix
    ./nix-ld.nix
    ./nix.nix
    ./nixpkgs.nix
    ./obsidian.nix
    ./opencl.nix
    ./openrgb
    ./openssl.nix
    ./opentablet.nix
    ./pdf.nix
    ./pipedream.nix
    ./plover.nix
    ./postgres.nix
    ./print.nix
    ./pulseaudio.nix
    ./pulumi.nix
    ./python.nix
    ./r2modman.nix
    ./ranger.nix
    ./rclone.nix
    ./recorder.nix
    ./remmina.nix
    ./restic.nix
    ./rtkit.nix
    ./rust.nix
    ./screenshot.nix
    ./secureboot.nix
    ./sensors.nix
    ./sqlite.nix
    ./sshuttle.nix
    ./steam
    ./sudo.nix
    ./sway.nix
    ./sxiv.nix
    ./tex.nix
    ./time.nix
    ./tmux.nix
    ./tools.nix
    ./torrent.nix
    ./turbovnc.nix
    ./udiskie.nix
    ./udisks2.nix
    ./user.nix
    ./ventoy.nix
    ./via.nix
    ./virtual.nix
    ./virtualgl.nix
    ./vlc.nix
    ./vnc.nix
    ./vulkan.nix
    ./waybar.nix
    ./windows.nix
    ./wowup.nix
    ./xbox.nix
    ./xdg.nix
    ./yubikey.nix
    ./zathura.nix
    ./zed.nix
  ];
}
