{ ... }:
{
  imports = [
    ./alacritty.nix
    ./blueman.nix
    ./clipboard.nix
    ./coolercontrol.nix
    ./core.nix
    ./corectrl.nix
    ./dircolors.nix
    ./docker
    ./fish
    ./flashfocus.nix
    ./foot.nix
    ./gammastep.nix
    ./gcloud.nix
    ./gemini.nix
    ./git
    ./ghostty.nix
    ./golang.nix
    ./gpgssh
    ./gpu.nix
    ./gtk.nix
    ./java.nix
    ./kanata
    ./kanshi
    ./kubernetes.nix
    ./lllm
    ./mako
    ./network.nix
    ./openrazer.nix
    ./openrgb.nix
    ./plover.nix
    ./polyaxon.nix
    ./ranger
    ./screenshot
    ./sway
    ./systemd.nix
    ./taskwarrior.nix
    ./terminal.nix
    ./udiskie.nix
    ./vr.nix
    ./waybar
    ./xdg.nix
    ./yazi
  ];
}
